

["ISO-4217::LRD"] = new Currency("LRD", "430", 2, "Liberian dollar", "$"), // or L$, LD$
["ISO-4217::LSL"] = new Currency("LSL", "426", 2, "Lesotho loti", "L"), // L or M (pl.)
["ISO-4217::LYD"] = new Currency("LYD", "434", 3, "Libyan dinar", "ل.د"), // or LD
["ISO-4217::MAD"] = new Currency("MAD", "504", 2, "Moroccan dirham", "د.م."),
["ISO-4217::MDL"] = new Currency("MDL", "498", 2, "Moldovan leu", "L"),
["ISO-4217::MGA"] = new Currency("MGA", "969", Z07, "Malagasy ariary", "Ar"),  // divided into five subunits rather than by a power of ten. 5 is 10 to the power of 0.69897...
["ISO-4217::MKD"] = new Currency("MKD", "807", 0, "Macedonian denar", "ден"),
["ISO-4217::MMK"] = new Currency("MMK", "104", 0, "Myanma kyat", "K"),
["ISO-4217::MNT"] = new Currency("MNT", "496", 2, "Mongolian tugrik", "₮"),
["ISO-4217::MOP"] = new Currency("MOP", "446", 2, "Macanese pataca", "MOP$"),
["ISO-4217::MRU"] = new Currency("MRU", "929", Z07, "Mauritanian ouguiya", "UM", validFrom: new DateTime(2018, 01, 01)), // divided into five subunits rather than by a power of ten. 5 is 10 to the power of 0.69897...
["ISO-4217::MUR"] = new Currency("MUR", "480", 2, "Mauritian rupee", "Rs"),
["ISO-4217::MVR"] = new Currency("MVR", "462", 2, "Maldivian rufiyaa", "Rf"), // or , MRf, MVR, .ރ or /-
["ISO-4217::MWK"] = new Currency("MWK", "454", 2, "Malawi kwacha", "MK"),
["ISO-4217::MXN"] = new Currency("MXN", "484", 2, "Mexican peso", "$"),
["ISO-4217::MXV"] = new Currency("MXV", "979", 2, "Mexican Unidad de Inversion (UDI) (funds code)", Currency.GenericCurrencySign),  // <==== not found
["ISO-4217::MYR"] = new Currency("MYR", "458", 2, "Malaysian ringgit", "RM"),
["ISO-4217::MZN"] = new Currency("MZN", "943", 2, "Mozambican metical", "MTn"), // or MTN
["ISO-4217::NAD"] = new Currency("NAD", "516", 2, "Namibian dollar", "N$"), // or $
["ISO-4217::NGN"] = new Currency("NGN", "566", 2, "Nigerian naira", "₦"),
["ISO-4217::NIO"] = new Currency("NIO", "558", 2, "Nicaraguan córdoba", "C$"),
["ISO-4217::NOK"] = new Currency("NOK", "578", 2, "Norwegian krone", "kr"),
["ISO-4217::NPR"] = new Currency("NPR", "524", 2, "Nepalese rupee", "Rs"), // or ₨ or रू
["ISO-4217::NZD"] = new Currency("NZD", "554", 2, "New Zealand dollar", "$"),
["ISO-4217::OMR"] = new Currency("OMR", "512", 3, "Omani rial", "ر.ع."),
["ISO-4217::PAB"] = new Currency("PAB", "590", 2, "Panamanian balboa", "B/."),
["ISO-4217::PEN"] = new Currency("PEN", "604", 2, "Peruvian sol", "S/."),
["ISO-4217::PGK"] = new Currency("PGK", "598", 2, "Papua New Guinean kina", "K"),
["ISO-4217::PHP"] = new Currency("PHP", "608", 2, "Philippine Peso", "₱"), // or P or PHP or PhP
["ISO-4217::PKR"] = new Currency("PKR", "586", 2, "Pakistani rupee", "Rs"),
["ISO-4217::PLN"] = new Currency("PLN", "985", 2, "Polish złoty", "zł"),
["ISO-4217::PYG"] = new Currency("PYG", "600", 0, "Paraguayan guaraní", "₲"),
["ISO-4217::QAR"] = new Currency("QAR", "634", 2, "Qatari riyal", "ر.ق"), // or QR
["ISO-4217::RON"] = new Currency("RON", "946", 2, "Romanian new leu", "lei"),
["ISO-4217::RSD"] = new Currency("RSD", "941", 2, "Serbian dinar", "РСД"), // or RSD (or дин or d./д)
["ISO-4217::RUB"] = new Currency("RUB", "643", 2, "Russian rouble", "₽"), // or R or руб (both onofficial)
["ISO-4217::RWF"] = new Currency("RWF", "646", 0, "Rwandan franc", "RFw"), // or RF, R₣
["ISO-4217::SAR"] = new Currency("SAR", "682", 2, "Saudi riyal", "ر.س"), // or SR (Latin) or ﷼‎ (Unicode)
["ISO-4217::SBD"] = new Currency("SBD", "090", 2, "Solomon Islands dollar", "SI$"),
["ISO-4217::SCR"] = new Currency("SCR", "690", 2, "Seychelles rupee", "SR"), // or SRe
["ISO-4217::SDG"] = new Currency("SDG", "938", 2, "Sudanese pound", "ج.س."),
["ISO-4217::SEK"] = new Currency("SEK", "752", 2, "Swedish krona/kronor", "kr"),
["ISO-4217::SGD"] = new Currency("SGD", "702", 2, "Singapore dollar", "S$"), // or $
["ISO-4217::SHP"] = new Currency("SHP", "654", 2, "Saint Helena pound", "£"),
["ISO-4217::SLL"] = new Currency("SLL", "694", 0, "Sierra Leonean leone", "Le"),
["ISO-4217::SOS"] = new Currency("SOS", "706", 2, "Somali shilling", "S"), // or Sh.So.
["ISO-4217::SRD"] = new Currency("SRD", "968", 2, "Surinamese dollar", "$"),
["ISO-4217::SSP"] = new Currency("SSP", "728", 2, "South Sudanese pound", "£"), // not sure about symbol...
["ISO-4217::SVC"] = new Currency("SVC", "222", 2, "El Salvador Colon", "₡"),
["ISO-4217::SYP"] = new Currency("SYP", "760", 2, "Syrian pound", "ܠ.ܣ.‏"), // or LS or £S (or £)
["ISO-4217::SZL"] = new Currency("SZL", "748", 2, "Swazi lilangeni", "L"), // or E (plural)
["ISO-4217::THB"] = new Currency("THB", "764", 2, "Thai baht", "฿"),
["ISO-4217::TJS"] = new Currency("TJS", "972", 2, "Tajikistani somoni", "смн"),
["ISO-4217::TMT"] = new Currency("TMT", "934", 2, "Turkmenistani manat", "m"), // or T?
["ISO-4217::TND"] = new Currency("TND", "788", 3, "Tunisian dinar", "د.ت"), // or DT (Latin)
["ISO-4217::TOP"] = new Currency("TOP", "776", 2, "Tongan paʻanga", "T$"), // (sometimes PT)
["ISO-4217::TRY"] = new Currency("TRY", "949", 2, "Turkish lira", "₺"),
["ISO-4217::TTD"] = new Currency("TTD", "780", 2, "Trinidad and Tobago dollar", "$"), // or TT$
["ISO-4217::TWD"] = new Currency("TWD", "901", 2, "New Taiwan dollar", "NT$"), // or $
["ISO-4217::TZS"] = new Currency("TZS", "834", 2, "Tanzanian shilling", "x/y"), // or TSh
["ISO-4217::UAH"] = new Currency("UAH", "980", 2, "Ukrainian hryvnia", "₴"),
["ISO-4217::UGX"] = new Currency("UGX", "800", 2, "Ugandan shilling", "USh"),
["ISO-4217::USD"] = new Currency("USD", "840", 2, "United States dollar", "$"), // or US$
["ISO-4217::USN"] = new Currency("USN", "997", 2, "United States dollar (next day) (funds code)", "$"),
["ISO-4217::UYI"] = new Currency("UYI", "940", 0, "Uruguay Peso en Unidades Indexadas (UI) (funds code)", Currency.GenericCurrencySign), // List two
["ISO-4217::UYU"] = new Currency("UYU", "858", 2, "Uruguayan peso", "$"), // or $U
["ISO-4217::UZS"] = new Currency("UZS", "860", 2, "Uzbekistan som", "лв"), // or сўм ?
["ISO-4217::VES"] = new Currency("VES", "928", 2, "Venezuelan Bolívar Soberano", "Bs.", validFrom: new DateTime(2018, 8, 20)), // or Bs.F. , Amendment 167 talks about delay but from multiple sources on the web the date seems to be 20 aug.
["ISO-4217::VND"] = new Currency("VND", "704", 0, "Vietnamese dong", "₫"),
["ISO-4217::VUV"] = new Currency("VUV", "548", 0, "Vanuatu vatu", "VT"),
["ISO-4217::WST"] = new Currency("WST", "882", 2, "Samoan tala", "WS$"), // sometimes SAT, ST or T
["ISO-4217::XAF"] = new Currency("XAF", "950", 0, "CFA franc BEAC", "FCFA"),
["ISO-4217::XAG"] = new Currency("XAG", "961", NotApplicable, "Silver (one troy ounce)", Currency.GenericCurrencySign),
["ISO-4217::XAU"] = new Currency("XAU", "959", NotApplicable, "Gold (one troy ounce)", Currency.GenericCurrencySign),
["ISO-4217::XBA"] = new Currency("XBA", "955", NotApplicable, "European Composite Unit (EURCO) (bond market unit)", Currency.GenericCurrencySign),
["ISO-4217::XBB"] = new Currency("XBB", "956", NotApplicable, "European Monetary Unit (E.M.U.-6) (bond market unit)", Currency.GenericCurrencySign),
["ISO-4217::XBC"] = new Currency("XBC", "957", NotApplicable, "European Unit of Account 9 (E.U.A.-9) (bond market unit)", Currency.GenericCurrencySign),
["ISO-4217::XBD"] = new Currency("XBD", "958", NotApplicable, "European Unit of Account 17 (E.U.A.-17) (bond market unit)", Currency.GenericCurrencySign),
["ISO-4217::XCD"] = new Currency("XCD", "951", 2, "East Caribbean dollar", "$"), // or EC$
["ISO-4217::XDR"] = new Currency("XDR", "960", NotApplicable, "Special drawing rights", Currency.GenericCurrencySign),
["ISO-4217::XOF"] = new Currency("XOF", "952", 0, "CFA franc BCEAO", "CFA"),
["ISO-4217::XPD"] = new Currency("XPD", "964", NotApplicable, "Palladium (one troy ounce)", Currency.GenericCurrencySign),
["ISO-4217::XPF"] = new Currency("XPF", "953", 0, "CFP franc", "F"),
["ISO-4217::XPT"] = new Currency("XPT", "962", NotApplicable, "Platinum (one troy ounce)", Currency.GenericCurrencySign),
["ISO-4217::XSU"] = new Currency("XSU", "994", NotApplicable, "SUCRE", Currency.GenericCurrencySign),
["ISO-4217::XTS"] = new Currency("XTS", "963", NotApplicable, "Code reserved for testing purposes", Currency.GenericCurrencySign),
["ISO-4217::XUA"] = new Currency("XUA", "965", NotApplicable, "ADB Unit of Account", Currency.GenericCurrencySign),
["ISO-4217::XXX"] = new Currency("XXX", "999", NotApplicable, "No currency", Currency.GenericCurrencySign),
["ISO-4217::YER"] = new Currency("YER", "886", 2, "Yemeni rial", "﷼"), // or ر.ي.‏‏ ?
["ISO-4217::ZAR"] = new Currency("ZAR", "710", 2, "South African rand", "R"),
["ISO-4217::ZMW"] = new Currency("ZMW", "967", 2, "Zambian kwacha", "ZK"), // or ZMW
["ISO-4217::ZWL"] = new Currency("ZWL", "932", 2, "Zimbabwean dollar", "$"),
["ISO-4217::STN"] = new Currency("STN", "930", 2, "Dobra", "Db", validFrom: new DateTime(2018, 1, 1)), // New Currency of São Tomé and Príncipe from 1 Jan 2018 (Amendment 164)
["ISO-4217::STD"] = new Currency("STD", "678", 2, "Dobra", "Db", validTo: new DateTime(2018, 1, 1)), // To be replaced Currency of São Tomé and Príncipe from 1 Jan 2018 (Amendment 164),  inflation has rendered the cêntimo obsolete
["ISO-4217::UYW"] = new Currency("UYW", "927", 2, "Unidad Previsional", "Db", validFrom: new DateTime(2018, 8, 29)), // The Central Bank of Uruguay is applying for new Fund currency code (Amendment 169)
