using System;

namespace Toman;

/// <summary>
/// Unit of Exchange for money.
/// </summary>
public class Currency
{

    /// <summary>
    /// The generic sign for unknown currency.
    /// </summary>
    /// <remarks>See : https://en.wikipedia.org/wiki/Currency_sign_(typography)</remarks>
    public const string UnknownCurrencySign = "¤";
    
    /// <summary>
    /// An AutoGenerated GUID for the currency.
    /// </summary>
    public Guid Id { get; private set; }
    
    /// <summary>
    /// Standard ISO-4217 code for the currency.
    /// </summary>
    public string Code { get; private set; }
    
    /// <summary>
    /// The numeric code for the currency.
    /// </summary>
    public string NumericCode { get; private set; }
    
    /// <summary>
    /// English name for the currency.
    /// </summary>
    public string EnglishName { get; private set; }
    
    /// <summary>
    /// The Currency symbol.
    /// </summary>
    public string Symbol { get; private set; }
    
    /// <summary>
    /// The number of decimal digits.
    /// </summary>
    public int DecimalCount { get; private set; }
    
    /// <summary>
    /// Persian name for the currency.
    /// </summary>
    public string PersianName { get; private set; }
    
    /// <summary>
    /// Location names (country) which listed for this currency.
    /// </summary>
    public string[] Locations { get; private set; }
    
    /// <summary>
    /// The wikipedia page url for the currency.
    /// </summary>
    public string? WikipediaUrl { get; private set; }
}